[install]
minimumReleaseAge = 3600
minimumReleaseAgeExcludes = [
  "vite-plus",
  "@voidzero-dev/vite-plus-core",
  "@voidzero-dev/vite-plus-test",
  "@voidzero-dev/vite-plus-prompts",
  "@oxc-project/runtime",
  "@oxlint/types",
  "oxlint",
  "oxfmt",
  "oxlint-tsgolint",
]
